name: Deploy

on:
  push:
    branches:
      - main

jobs:
  magic:
    runs-on: ubuntu-latest
    name: Magic
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'workers.dev/magic'
          command: deploy
  preston:
    runs-on: ubuntu-latest
    name: Preston
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'workers.dev/preston'
          command: deploy
